### ISSUE TITLE
Collaboration?

### ISSUE THREAD

**Issue by erwanp** [it-scientists/pyspectra#9]
Hello,

I recently found out about your project! 
I'm a core developer at the [radis](https://github.com/radis/radis) project, which is an open source project for emission/absorption infrared spectroscopy. But it also features a lot of post-processing tools (see [there](https://radis.readthedocs.io/en/latest/spectrum/spectrum.html#label-spectrum) ) used by other spectral codes, and a complete documentation... but there are definitly less filtering tools than the one you're showing in #7 : do you think there could be synergies with `pyspectra`? Are you interested in a co-development ?

Erwan

**Comment by rguliev** [comment]
Hi,

Thanks for your interest. Sure, I am interested in collaboration) Can we appoint a call to discuss it in details?

P.S. If you do not mind, let's proceed this discussion in email. It is not an issue:)
